### ISSUE TITLE
WoWGatheringNodes breaking Routes

### ISSUE THREAD

**Issue by Nevcairiel** [SLOKnightfall/WoWGatheringNodes#2]
This addon is causing errors in Routes, for example:
https://www.wowace.com/projects/routes/issues/126

Hooking directly into other addons and feeding them bad data seems like a bad design. Should just import data into GatherMate2 and not hook also Routes etc.

**Comment by SLOKnightfall** [comment]
I believe that you misunderstand how WoWGatheringNodes work.  

~~First off WoWGathering Nodes does not hook into Routes. Based on the error line number in Routes, the issue appears to be that Routes is not getting back the correct localization info for custom data, not due to hooking or feeding bad data.~~ Actually looking at my code I see now that I did actually hook into routes to provide a way for it to get custom node localization info

Second, when a user uses the GatherMate import for WoWGatheringNodes, all data is imported into the GathermateDB.  For nodes not currently supported by GatherMate the wowhead DB entry for the node is uses to prevent any issues from Gathermate's numbering of node types.   WoWGathering Nodes then adds these custom nodes to the appropriate tables in Gathermate.  You can tell that the data is good because the new nodes show up on the world map.  The reason that the nodes disappear when WoWGatheringNodes is disabled is because the code that adds the custom nodes is not run and Gathermate ignores the node data in the DB is not in its list, not because the node data was not added to the DB.

Now that I know what data Routes needs I can try to fix the issue to make sure that the localization info for custom ids are getting added correctly.

**Comment by SLOKnightfall** [comment]
Fixed.  Turns out issue was I had inverted an else statement and the hooked fix was not actually being loaded.  Swapping them now correctly creates the hook and uses the modified lookup on the custom nodes.
